.TH "eye" 1 "January 17, 2019" "eye 0.9.0-ed80924/master" "eye"
.SH NAME
eye
\- Configuration Lookup service
.SH SYNOPSIS
eye  [\-c|\-\-config /srv/eye/conf/eye.conf] [\-h|\-\-help] [\-\-version]
.SH DESCRIPTION
Eye stores threshold configuration profiles in a Format suitable for Cyclone metric monitoring.

.SH OPTIONS
.TP
\-c,\-\-config /srv/eye/conf/eye.conf
Configuration file
.TP
\-h,\-\-help
Show usage message
.TP
\-\-version
Show version
.SH AUTHOR
Jörg Pernfuß
